-- ============================================================
--  TerraSupply — Migración v6: número de pedido público
--  Reemplaza el sitio externo de seguimiento (GitHub Pages) por
--  una página propia dentro de la app. Este número corto es el
--  que ven los clientes (ej. #1024) en vez del id uuid interno.
--  Ejecuta este script en: Supabase → SQL Editor → New Query
--  (Aplícalo después de supabase_migration_ventas_v5.sql)
-- ============================================================

-- ─────────────────────────────────────────
--  1. NUEVA COLUMNA EN SALES
--     Identity: se autoasigna en cada venta nueva y también
--     rellena las ventas existentes en orden, empezando en 1000.
-- ─────────────────────────────────────────
alter table sales
  add column if not exists order_number bigint generated by default as identity (start with 1000);

alter table sales
  add constraint sales_order_number_unique unique (order_number);

-- ─────────────────────────────────────────
--  FIN DE LA MIGRACIÓN
-- ─────────────────────────────────────────
